language: android

env:
  global:
    #key
    - secure: "JkM6LHw6WkcRqMxXOdAZ9ORiHB6BLvLrJ5WeYCSvGigX2BUQRd5wmUmEkFj82WoQFiq928+LonkomDAKYKTJ0DpgJ6CK8Epif/ilTM665dZahOVf7ktYcr7TqUGhHW/hioVrbb0kgVyi0i1Rw1feVB3S2LKbvInY59uRqbjeg4vY5GCGJ0Tc33WEeOEWNljBAFDbOOgdG90mCJG1A5z30iYx06Tm3ceBF+RH/noPi51erNdsi6bsDisNwFodBq90VA18/B1vRgwfJFU3/ezPzc78V1Mhg9DTP3G7z4n6R2xZalhqkqk9j9xMsr0zyvSI7qs2a8GrEwRaaXStKD0p1HmaDUUxvZckuleZQDHkJ3ycyrdkr4n9ylAvGtQEkyizEoyEeQNlY+RLTRuZrSWDdPApJkbLdFWsjvka1/zt1APT2AG+wKMUuAR6XCnEBE7YsUXJk1kdD6MIDesWXM4J5bCteCFzGk6rbM7TiSaLNPUDJXXvW3eGkGsc9H7u7caJQBMvdGDDAc/BKO6BNE02jDXRQrXD2nr/6FyioorMKsJwIZPf7/AzYsPhK3hAXF3e78pTxsP4v4B39y2mtFnDcoLCebXHH6AsZft3AN8aonN1V4I6eB9X/LjkV9dBC+DE8EEV0dMCIVcqagdFyO+lqT/qeLICtDmyVzZPo4RdZpQ="
    #store
    - secure: "xxJJE03cse/NYG+7L8B/9Q3qdEV/NOjbLn4lQVzgVYsEThItbTi98h6yC14wGOf6vTJDKyVaWeTxYkcSvKLqLRfc7aSXmWvHjzPu9PF/wrnY9akj/1HPT7/fV0gFDByq1Wrl/hj7NFLa69uISzv955OEeQRwh1zf0xamb8JdoujETWpPw2kC/78jKmnbFSGWgZ56cj3ZYQ0JB8ZtowqHbKC9Tc6/Uou2Lfvldq8RJDOScbGPmOUZX0cEPyiUUNs4C0oWlTDwbJ0CjFYYp+tqxI/YsVW/YSYOrkY7BP1Hdhp4oDVeBAIkwIlJB/WLJDrDIjHqJq7fBaIMO87ij/vJAb6Y0zorAdSZd1QMqt6dPO/iUEeKedOcAeHJL6ouSpG2CNmGm9QngvOTIm6r3GCWiIU088nQIfiNkT0FkPshxyaUdsOPmNnwrCxZrTt+cgNsvHdvvcR69XAWqz1df6JDS0rjShcX2NVbeNXHLM/ax5Z2JR8VtDGrwgbf0VJQkt05bHlPBApf3oHjkM8ADezWkSTI5JsWjHqH+rKHaF/uKnLjqWEhPdYqdt1XDscOFjnnKjUEQ/IuSYSKNcwmDPHXRvKbDBKbg0iJVoru5H0endV1PutofURYl4QEi9nWwo8ELgIAgK/KNb37dlE8LSWZXt67BDrBCRQ38HY0/ZDUwt8="

android:
  components:
    - android-22
    - build-tools-22.0.1
    - extra-android-support
    - extra-android-m2repository
#    - sys-img-armeabi-v7a-android-21

script:
#  - ./gradlew build
  - ./gradlew --debug --stacktrace assembleRelease crashlyticsUploadDistributionRelease
